version: '3.3'
services:
  #Postgres
  sonar_db:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      PGDATA: /var/lib/postgresql/data/some_name/
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: sonar_db
  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - sonar_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    container_name: sonarqube
  jenkins:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    container_name: jenkins

  portainer:
    image: portainer/portainer
    privileged: true
    restart: always
    ports:
      - "11000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    container_name: portainer

volumes:
  portainer_data:
    driver: local
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

# Commande pour retrouver le mot de passe de jenkins : docker exec -it jenkins cat /opt/bitnami/jenkins/jenkins_home/secrets/initialAdminPassword 
# User : user 
